apiVersion: cilium.io/v2
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: chris-pc
  interfaces:
    - eno+
  externalIPs: true
  loadBalancerIPs: true
