apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium-config

commonLabels:
  app: cilium
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: cilium-config

namespace: kube-system

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
  # - default-ciliumbgpadvertisement.yaml
  # - default-ciliumbgpclusterconfig.yaml
  # - default-ciliumbgppeerconfig.yaml
  - default-ciliumbgppeeringpolicy.yaml
  - default-ciliuml2announcementpolicy.yaml
  - default-ciliumloadbalancerippool.yaml
